[package]
name = "mabel-proto"
description = "Prost-generated types for the normative mabel schemas"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
prost.workspace = true

[build-dependencies]
prost-build.workspace = true
protoc-bin-vendored.workspace = true
